[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xffa198"
index = 17

[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xa9b665" 
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

# [env]
#TERM = "xterm-256color"

[font]
size = 14.0

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1


[window]
decorations = "None"
opacity = 0.95
blur = true
dynamic_padding = true
